### ISSUE TITLE
Add meta tag to make it mobile device friendly

### ISSUE THREAD

**Issue by jonnypetraglia** [THREExPENNYco/rubyproject#1]
Add a meta tag to your `app/views/layouts/application.html.erb` file so you site looks good on mobile devices.
It should look like this:
`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by THREExPENNYco** [comment]
Added the meta tag. Displaying cleaner on mobile now. Thank you 👍

**Comment by jonnypetraglia** [comment]
Nice! You can now officially close your first Github issue! :grinning:
